### ISSUE TITLE
Enable Log Aggregation for Trino

### ISSUE THREAD

**Issue by maltesander** [stackabletech/trino-operator#376]
See https://github.com/stackabletech/hbase-operator/issues/291 and https://github.com/stackabletech/docker-images/pull/283 for reference.

This is part of https://github.com/stackabletech/issues/issues/288

### TODO

- [ ] Research Trino / Airlift logging:
  - [ ] Logs customizable? https://github.com/trinodb/trino/issues/9969
  - [ ] XML log format possible (it seems JSON could be configured)? 
  - [ ] Trino logging options https://trino.io/docs/current/admin/properties-logging.html
- [ ] Prepare Trino docker image with vector
- [ ] Bump to latest operator-rs and stackable versions
- [ ] Enable logging in operator
