### ISSUE TITLE
Rework Trino TLS / Auth structs: Change authentication to list of AuthenticationClasses

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/trino-operator#401]
Follow-up of https://github.com/stackabletech/trino-operator/issues/395
Part of https://github.com/stackabletech/issues/issues/293

## TODO:

- [x] Add bcrypt to docker image https://github.com/stackabletech/docker-images/pull/385
- [x] Fix static provider https://github.com/stackabletech/operator-rs/pull/597
- [x] Adapt operator https://github.com/stackabletech/trino-operator/pull/434
