### ISSUE TITLE
Document where to find production ready rego rules

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/trino-operator#580]
```[tasklist]
### Tasks
- [x] Link to integration tests folder
- [x] Link to Trino docs which describe the schema
- [x] Document all differences that don't apply to our rules, see [comment](https://github.com/stackabletech/trino-operator/issues/580#issuecomment-2092705697) below
```

**Comment by siegfriedweber** [comment]
Differences to the [documentation of the File-based access control](https://trino.io/docs/current/security/file-system-access-control.html):
* The "System-level access control" is implemented but not the "Catalog-level access control".
* The rules are defined in a Rego file instead of a JSON file, so the Configuration section does not apply.
* Roles are not checked, only user and group.
* The allow property of the catalog rules accepts only the new values "all", "read-only", and "none", but not the legacy values "true" and "false".
* Principal rules are deprecated and not implemented.

The documentation does not fully describe the file-based access control implemented in Trino. For instance, the documentation states:

> If neither impersonation nor principal rules are defined, impersonation is not allowed.

But actually it is always allowed to impersonate oneself.
There are a lot of these subtleties and the Rego rules try to implement the Java implementation as close as possible and not necessarily the documentation. However, it was not possible to exactly implement every line of Java in Rego, but it would take things too far to list all of them.
